// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOi-OUBNDX5LKUuEDZ2fh1dZJZlNzNcI',
    appId: '1:139226985617:web:2eb6a3bc2c8565f3107b30',
    messagingSenderId: '139226985617',
    projectId: 'khawatir-d3394',
    authDomain: 'khawatir-d3394.firebaseapp.com',
    storageBucket: 'khawatir-d3394.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB__8M4cyjkIbLraBALwB6gVSNqv3vgXNk',
    appId: '1:139226985617:android:36b0eabdeefd431a107b30',
    messagingSenderId: '139226985617',
    projectId: 'khawatir-d3394',
    storageBucket: 'khawatir-d3394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2ByRfDrJENqcVPVw6TZhf2C8wzSjXMc',
    appId: '1:139226985617:ios:2ea9b7104e1ff056107b30',
    messagingSenderId: '139226985617',
    projectId: 'khawatir-d3394',
    storageBucket: 'khawatir-d3394.appspot.com',
    iosBundleId: 'com.example.khawatir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw2ByRfDrJENqcVPVw6TZhf2C8wzSjXMc',
    appId: '1:139226985617:ios:a122a7bdb58b9703107b30',
    messagingSenderId: '139226985617',
    projectId: 'khawatir-d3394',
    storageBucket: 'khawatir-d3394.appspot.com',
    iosBundleId: 'com.example.khawatir.RunnerTests',
  );
}
